name: webdriverio-ci

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: args='--headless' npm run test
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs